### ISSUE TITLE
Text wayyyy too large

### ISSUE THREAD

**Issue by Milkshakes00** [Timidger/autowikiabot-py#31]
http://www.reddit.com/r/dyinglight/comments/2u9cvi/i_know_cars_can_break_your_fall_but_this_is/co6dpz3

**Comment by Timidger** [comment]
Yeah, sorry about that. I have since fixed that already (as you can see [here](https://www.reddit.com/r/autowikiabot/comments/2ucgvf/large_text_test/)). Thank you very much for the bug report, have a good day :)
